---

- name: "04.1.1 - make sure necessary kernel modules are enabled to start on boot"
  copy:
    content: |
      {{ item }}
    dest: "{{ __k8s_modprobe_load_d_dir }}/{{ item }}.conf"
  become: yes
  loop:
    - overlay
    - br_netfilter

- name: "04.1.2 - make sure required modules are configure to be loaded with specified parameters"
  modprobe:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - overlay
    - br_netfilter

- name: "04.2 - setup sysctl variables"
  sysctl:
    name: "{{ item.key }}"
    state: present
    value: "{{ item.value }}"
    sysctl_file: "{{ __k8s_sysctl_d_conf_file }}"
    sysctl_set: yes
    reload: yes
  become: yes
  with_items:
    # disable ipv6
    - key: net.ipv6.conf.all.disable_ipv6
      value: 1
    - key: net.ipv6.conf.default.disable_ipv6
      value: 1
    - key: net.ipv6.conf.lo.disable_ipv6
      value: 1
    # required for k8s iptables configuration
    - key: net.bridge.bridge-nf-call-iptables
      value: 1
    - key: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - key: net.ipv4.ip_forward
      value: 1
    - key: net.ipv4.conf.all.forwarding
      value: 1
